name: pharos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.1
  lottie: ^3.1.2
  tflite_v2: ^1.0.0
#  tflite_flutter: ^0.10.4
#  tflite: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/labels.txt
    - assets/model_unquant.tflite
    - assets/ai.json